server:
  port: 8383
  tomcat:
    connection-timeout: 600000
#    context-path: /planoCycle
#    context-path: /cocacola-planocycle-api
spring:
  datasource:
    url: ${PLANO_URL}
    username: ${PLANO_USERNAME}
    password: ${PLANO_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 10
      # 连接池最大连接数，默认是10
      maximum-pool-size: 30
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 30MB
  jackson:
    time-zone: Asia/Tokyo
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: /
# 环境变量
SystemPath: ${PORTAL_URL}
projectIds: ${projectIds}
bucketNames: ${bucketNames}
ptsDownPath: ${ptsDownPath}
productDownPath: ${productDownPath}
smartPath: ${smartPath}